/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppLogin {}
  interface AppLregister {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface DocDashboard {}
  interface PatientDashboard {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppLregisterElement extends Components.AppLregister, HTMLStencilElement {}
  var HTMLAppLregisterElement: {
    prototype: HTMLAppLregisterElement;
    new (): HTMLAppLregisterElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDocDashboardElement extends Components.DocDashboard, HTMLStencilElement {}
  var HTMLDocDashboardElement: {
    prototype: HTMLDocDashboardElement;
    new (): HTMLDocDashboardElement;
  };

  interface HTMLPatientDashboardElement extends Components.PatientDashboard, HTMLStencilElement {}
  var HTMLPatientDashboardElement: {
    prototype: HTMLPatientDashboardElement;
    new (): HTMLPatientDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-login': HTMLAppLoginElement;
    'app-lregister': HTMLAppLregisterElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'doc-dashboard': HTMLDocDashboardElement;
    'patient-dashboard': HTMLPatientDashboardElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppLogin {}
  interface AppLregister {}
  interface AppProfile {
    'name'?: string;
  }
  interface AppRoot {}
  interface DocDashboard {}
  interface PatientDashboard {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-login': AppLogin;
    'app-lregister': AppLregister;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'doc-dashboard': DocDashboard;
    'patient-dashboard': PatientDashboard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-login': LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
      'app-lregister': LocalJSX.AppLregister & JSXBase.HTMLAttributes<HTMLAppLregisterElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'doc-dashboard': LocalJSX.DocDashboard & JSXBase.HTMLAttributes<HTMLDocDashboardElement>;
      'patient-dashboard': LocalJSX.PatientDashboard & JSXBase.HTMLAttributes<HTMLPatientDashboardElement>;
    }
  }
}


